### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by aiturralde** [ANDRESI-Training/ArchCapital#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by jmorera1** [comment]
test

**Comment by jyeragi** [comment]
comment for test workshop

**Comment by RAGGZ001** [comment]
Hello Andres...

**Comment by kymc1998** [comment]
hi

**Comment by vimmidisetti123** [comment]
Hello Hello

**Comment by YongToulou** [comment]
i could not install Git locally.

**Comment by PreetSingh007** [comment]
Some comment

**Comment by jlamanna00** [comment]
how now brown cow

**Comment by jarias51** [comment]
Arch class

**Comment by jlangbein-arch** [comment]
Collaboration is key.

**Comment by NickTimbers** [comment]
:)

**Comment by mitchevk** [comment]
Class Training

**Comment by DarthSudo** [comment]
Pick me! Pick Me!

**Comment by jonelson-git-challenge** [comment]
test

**Comment by veerarajmaru** [comment]
test

**Comment by DGK1981** [comment]
I am commenting.  Git and Git Hub was installed on my laptop via the Software Center

**Comment by jwatkins-arch** [comment]
Testing from Arch

**Comment by radhikari-arch** [comment]
hello world!

**Comment by sraza5** [comment]
Hello

**Comment by agiordanoarchcap** [comment]
good afternoon

**Comment by cliffseals** [comment]
howdy

**Comment by AnshumanSingh2** [comment]
Hello !!

**Comment by LateefS** [comment]
Good Afternoon

**Comment by thejptnaz** [comment]
test

**Comment by TSNArch** [comment]
Hi All

**Comment by lbelvery** [comment]
hello

**Comment by cacarroll86** [comment]
test

**Comment by sraza5** [comment]
Test!!!!!

**Comment by kittu-79** [comment]
test

**Comment by shoodgit** [comment]
hello
